language: node_js
node_js:
  - 6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lua5.1-dev
      - g++-4.8

before_install:
  - export CXX=g++-4.8
  - $CXX --version

after_success: npm run coverage
